import sharp from "sharp";
import { statSync } from "node:fs";
// [src, out, maxWidth, quality]
const jobs = [
  ["public/assets/src/bg-layer1-v2.png", "public/assets/opt/bg-layer1.webp", 2400, 82],
  [
    "public/assets/src/blacksun-layer2.png",
    "public/assets/opt/blacksun-layer2.webp",
    1024,
    85,
  ],
  [
    "public/assets/src/blacksun2-layer3-v2.png",
    "public/assets/opt/blacksun2-layer3.webp",
    1748,
    85,
  ],
  [
    "public/assets/src/minisun-layer4.png",
    "public/assets/opt/minisun-layer4.webp",
    400,
    90,
  ],
  [
    "public/assets/src/suncoverbg-layer5.png",
    "public/assets/opt/suncoverbg-layer5.webp",
    2600,
    82,
  ],
  [
    "public/assets/src/mainart-layer6.png",
    "public/assets/opt/mainart-layer6.webp",
    2600,
    84,
  ],
  ["public/assets/src/bottom.png", "public/assets/opt/bottom.webp", 2600, 84],
  ["public/assets/src/hand.png", "public/assets/opt/hand.webp", 800, 86],
  ["public/assets/src/veena.png", "public/assets/opt/veena.webp", 1400, 86],
  ["public/assets/src/banner.png", "public/assets/opt/banner.webp", 700, 86],
  ["public/assets/src/divider.png", "public/assets/opt/divider.webp", 1100, 90],
  ["public/assets/src/comingsoon.png", "public/assets/opt/comingsoon.webp", 2600, 84],
  [
    "public/assets/src/mainart-mobile.png",
    "public/assets/opt/mainart-mobile.webp",
    1400,
    84,
  ],
  ["public/logo/src/hitk-logo.png", "public/logo/opt/hitk-logo.webp", 500, 86],
  ["public/logo/src/iic-logo.png", "public/logo/opt/iic-logo.webp", 800, 86],
  ["public/logo/src/eclecia-logo.png", "public/logo/opt/eclecia-logo.webp", 500, 86],
  [
    "public/logo/src/eclecia-wordmark-blacker.png",
    "public/logo/opt/eclecia-wordmark-blacker.webp",
    800,
    86,
  ],
];
for (const [src, out, w, q] of jobs) {
  await sharp(src)
    .resize({ width: w, withoutEnlargement: true })
    .webp({ quality: q, alphaQuality: 90, effort: 6 })
    .toFile(out);
  console.log(
    out,
    (statSync(src).size / 1e6).toFixed(2),
    "MB ->",
    (statSync(out).size / 1e6).toFixed(2),
    "MB",
  );
}

// Tiny blurred stand-in for the sky, inlined as a data URI so the first paint isn't black.
{
  const buf = await sharp("public/assets/opt/bg-layer1.webp").resize({ width: 32 }).blur(1.2).jpeg({ quality: 45 }).toBuffer();
  const uri = `data:image/jpeg;base64,${buf.toString("base64")}`;
  const { writeFileSync } = await import("node:fs");
  writeFileSync(
    "app/lqip.ts",
    `// Tiny blurred stand-in for the sky (generated by scripts/optimize-assets.mjs). Paints before any image loads.\nexport const SKY_LQIP = ${JSON.stringify(uri)};\n`,
  );
  console.log("app/lqip.ts", uri.length, "chars");
}
